import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Main from "../HomePageComponents/Main";
import Footer from "@/HomePageComponents/Footer";
import { CartProvider } from "@/context/CartContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Eshoe",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {" "}
        <link
          rel="icon"
          href="https://p7.hiclipart.com/preview/722/1001/154/shoe-converse-sneakers-canvas-shoes.jpg"
        />
      </head>
      <body className={inter.className}>
        <CartProvider>
          <Main />
          {children}
          <Footer />
        </CartProvider>
      </body>
    </html>
  );
}
