import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Eshoe",
  description: "Generated by create next app",

};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>      <link rel="icon" href="https://p7.hiclipart.com/preview/722/1001/154/shoe-converse-sneakers-canvas-shoes.jpg" /></head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
